#!/usr/bin/env bash
set -euo pipefail

# ─── QueryFuser Self-Hosted Setup ─────────────────────────────────────────────
#
# This script automates the full setup:
#   1. Installs Docker (if needed)
#   2. Prompts for license key and BigQuery project
#   3. Auto-generates all secrets and database credentials
#   4. Starts PostgreSQL + QueryFuser via docker compose
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/queryfuser/deploy/main/setup.sh | bash
#
# Or clone and run:
#   git clone https://github.com/queryfuser/deploy.git && cd deploy && bash setup.sh
# ──────────────────────────────────────────────────────────────────────────────

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
error() { echo -e "${RED}✗${NC} $*"; exit 1; }
ask()   { echo -en "${BOLD}$1${NC}"; read -r "$2"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       QueryFuser Self-Hosted Setup           ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── 0. Check we're in the right directory ────────────────────────────────────

if [[ ! -f "$DEPLOY_DIR/docker-compose.yml" ]]; then
    if [[ ! -d "queryfuser-deploy" ]]; then
        echo "Cloning deployment repo..."
        git clone https://github.com/queryfuser/deploy.git queryfuser-deploy
    fi
    cd queryfuser-deploy
    DEPLOY_DIR="$(pwd)"
fi
cd "$DEPLOY_DIR"

# ── 1. Docker ────────────────────────────────────────────────────────────────

echo -e "\n${BOLD}[1/3] Checking Docker...${NC}"
if ! command -v docker &>/dev/null; then
    warn "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    info "Docker installed. You may need to log out and back in for group changes."
else
    info "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"
fi

if ! docker compose version &>/dev/null; then
    error "docker compose plugin not found. Install it: https://docs.docker.com/compose/install/"
fi

# ── 2. Configuration ────────────────────────────────────────────────────────

echo -e "\n${BOLD}[2/3] Configuration...${NC}"

if [[ -f .env ]]; then
    warn ".env file already exists."
    ask "Overwrite? (y/N) " OVERWRITE
    if [[ "${OVERWRITE:-n}" != "y" && "${OVERWRITE:-n}" != "Y" ]]; then
        info "Keeping existing .env"
    else
        rm .env
    fi
fi

if [[ ! -f .env ]]; then
    echo ""
    ask "QueryFuser license key (from queryfuser.com/deploy): " LICENSE_KEY

    if [[ -z "$LICENSE_KEY" ]]; then
        error "License key is required. Get one at https://queryfuser.com/deploy"
    fi

    echo ""
    echo -e "${BOLD}BigQuery Configuration${NC}"
    echo -e "The proxy uses your VM's service account to access BigQuery."
    echo -e "Make sure the CE default service account has the BigQuery Data Viewer"
    echo -e "and BigQuery Job User roles."
    echo ""
    ask "GCP project ID (for BigQuery): " BQ_PROJECT_ID
    ask "BigQuery dataset (optional) []: " BQ_DATASET
    BQ_DATASET="${BQ_DATASET:-}"

    if [[ -z "$BQ_PROJECT_ID" ]]; then
        error "GCP project ID is required for BigQuery access."
    fi

    # Auto-generate all secrets
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48)
    MASTER_KEY=$(openssl rand -hex 32)

    cat > .env <<EOF
# Auto-generated by setup.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Bundled PostgreSQL password (auto-generated)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT signing secret (auto-generated)
JWT_SECRET=${JWT_SECRET}

# Encryption key for credentials at rest (auto-generated)
MASTER_KEY=${MASTER_KEY}

# License key
QUERYFUSER_LICENSE_KEY=${LICENSE_KEY}

# BigQuery
BIGQUERY_PROJECT_ID=${BQ_PROJECT_ID}
BIGQUERY_DATASET=${BQ_DATASET}
EOF

    info "Generated .env (all secrets auto-generated)"
    echo ""

    # Optional: Google OAuth
    ask "Set up Google Sign-In? (y/N) " SETUP_GOOGLE
    if [[ "${SETUP_GOOGLE:-n}" == "y" || "${SETUP_GOOGLE:-n}" == "Y" ]]; then
        ask "Google Client ID: " GOOGLE_CLIENT_ID
        ask "Google Client Secret: " GOOGLE_CLIENT_SECRET
        ask "OAuth Redirect URI (e.g. https://your-domain.com/auth/google/callback): " OAUTH_REDIRECT_URI
        cat >> .env <<EOF

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
EOF
        info "Added Google OAuth config"
    fi
fi

# ── 3. Start QueryFuser ─────────────────────────────────────────────────────

echo -e "\n${BOLD}[3/3] Starting QueryFuser...${NC}"

docker compose pull
docker compose up -d

echo ""

# Wait for health
echo -n "Waiting for QueryFuser to start..."
for i in $(seq 1 60); do
    if curl -sf http://localhost:3001 &>/dev/null; then
        echo ""
        info "QueryFuser is running!"
        break
    fi
    if [[ $i -eq 60 ]]; then
        echo ""
        warn "Timed out waiting. Check logs with: docker compose logs"
    fi
    echo -n "."
    sleep 2
done

# Get external IP
EXTERNAL_IP=$(curl -sf http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -H "Metadata-Flavor: Google" 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║          Setup Complete! 🎉                  ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  http://${EXTERNAL_IP}:3001"
echo -e "  ${BOLD}Proxy:${NC}      ${EXTERNAL_IP}:5433 (PostgreSQL)"
echo ""
echo -e "  ${BOLD}Connect your BI tool:${NC}"
echo -e "    Host:     ${EXTERNAL_IP}"
echo -e "    Port:     5433"
echo -e "    Username: (create one in the dashboard)"
echo -e "    Password: (set in the dashboard)"
echo ""
echo -e "  ${BOLD}BigQuery:${NC}  Uses the VM's default service account (no credentials needed)."
echo -e "  ${BOLD}Database:${NC}  PostgreSQL runs in Docker (data stored in pgdata volume)."
echo -e "             To migrate to Cloud SQL later, update DATABASE_URL in .env."
echo ""
echo -e "  ${BOLD}Firewall:${NC}  Make sure ports 3001 and 5433 are open."
echo ""
echo -e "  ${BOLD}Logs:${NC}      docker compose logs -f"
echo -e "  ${BOLD}Stop:${NC}      docker compose down"
echo -e "  ${BOLD}Update:${NC}    docker compose pull && docker compose up -d"
echo ""
