#!/usr/bin/env bash
set -euo pipefail

# ─── QueryFuser Self-Hosted Setup ─────────────────────────────────────────────
#
# This script automates the full setup:
#   1. Installs Docker (if needed)
#   2. Prompts for license key
#   3. Auto-generates all secrets and database credentials
#   4. Starts PostgreSQL + QueryFuser via docker compose
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/queryfuser/deploy/main/setup.sh | bash
#
# Or clone and run:
#   git clone https://github.com/queryfuser/deploy.git && cd deploy && bash setup.sh
# ──────────────────────────────────────────────────────────────────────────────

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
error() { echo -e "${RED}✗${NC} $*"; exit 1; }
ask()   { echo -en "${BOLD}$1${NC}"; read -r "$2"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       QueryFuser Self-Hosted Setup           ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── 0. Check we're in the right directory ────────────────────────────────────

if [[ ! -f "$DEPLOY_DIR/docker-compose.yml" ]]; then
    # Need git to clone — install if missing
    if ! command -v git &>/dev/null; then
        warn "git not found. Installing..."
        if command -v apt-get &>/dev/null; then
            sudo apt-get update -qq && sudo apt-get install -y -qq git
        elif command -v yum &>/dev/null; then
            sudo yum install -y -q git
        else
            error "git is not installed and could not be installed automatically. Please install git and try again."
        fi
        info "git installed"
    fi
    if [[ ! -d "queryfuser-deploy" ]]; then
        echo "Cloning deployment repo..."
        git clone https://github.com/queryfuser/deploy.git queryfuser-deploy
    fi
    cd queryfuser-deploy
    DEPLOY_DIR="$(pwd)"
fi
cd "$DEPLOY_DIR"

# ── 1. Docker ────────────────────────────────────────────────────────────────

echo -e "\n${BOLD}[1/3] Checking Docker...${NC}"
if ! command -v docker &>/dev/null; then
    warn "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    info "Docker installed. You may need to log out and back in for group changes."
else
    info "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"
fi

if ! docker compose version &>/dev/null; then
    error "docker compose plugin not found. Install it: https://docs.docker.com/compose/install/"
fi

# ── 2. Configuration ────────────────────────────────────────────────────────

echo -e "\n${BOLD}[2/3] Configuration...${NC}"

if [[ -f .env ]]; then
    warn ".env file already exists."
    ask "Overwrite? (y/N) " OVERWRITE
    if [[ "${OVERWRITE:-n}" != "y" && "${OVERWRITE:-n}" != "Y" ]]; then
        info "Keeping existing .env"
    else
        rm .env
    fi
fi

if [[ ! -f .env ]]; then
    echo ""
    ask "QueryFuser license key (from queryfuser.com/deploy): " LICENSE_KEY

    if [[ -z "$LICENSE_KEY" ]]; then
        error "License key is required. Get one at https://queryfuser.com/deploy"
    fi

    # Auto-generate all secrets
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48)
    MASTER_KEY=$(openssl rand -hex 32)

    cat > .env <<EOF
# Auto-generated by setup.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Self-hosted mode (hides SA JSON upload, uses VM service account)
SELF_HOSTED=true

# Bundled PostgreSQL — activates the db container
COMPOSE_PROFILES=db
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT signing secret (auto-generated)
JWT_SECRET=${JWT_SECRET}

# Encryption key for credentials at rest (auto-generated)
MASTER_KEY=${MASTER_KEY}

# License key
QUERYFUSER_LICENSE_KEY=${LICENSE_KEY}
EOF

    info "Generated .env (all secrets auto-generated)"
fi

# ── 3. Start QueryFuser ─────────────────────────────────────────────────────

echo -e "\n${BOLD}[3/3] Starting QueryFuser...${NC}"

docker compose pull
docker compose up -d

echo ""

# Wait for health
echo -n "Waiting for QueryFuser to start..."
for i in $(seq 1 60); do
    if curl -sf http://localhost:3001 &>/dev/null; then
        echo ""
        info "QueryFuser is running!"
        break
    fi
    if [[ $i -eq 60 ]]; then
        echo ""
        warn "Timed out waiting. Check logs with: docker compose logs"
    fi
    echo -n "."
    sleep 2
done

# Get external IP
EXTERNAL_IP=$(curl -sf http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -H "Metadata-Flavor: Google" 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║          Setup Complete! 🎉                  ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  http://${EXTERNAL_IP}:3001"
echo -e "  ${BOLD}Proxy:${NC}      ${EXTERNAL_IP}:5433 (PostgreSQL)"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "    1. Open the dashboard and register your first user"
echo -e "    2. Create a BigQuery project (enter your GCP project ID + dataset)"
echo -e "    3. Point your BI tool at ${EXTERNAL_IP}:5433"
echo ""
echo -e "  ${BOLD}BigQuery:${NC}  Uses the VM's default service account (ADC)."
echo -e "             Make sure it has BigQuery Data Viewer, Job User, and BigQuery User roles."
echo -e "  ${BOLD}Database:${NC}  PostgreSQL runs in Docker (data in pgdata volume)."
echo -e "             To migrate to Cloud SQL later, see README.md."
echo ""
echo -e "  ${BOLD}Firewall:${NC}  Make sure ports 3001 and 5433 are open."
echo ""
echo -e "  ${BOLD}Logs:${NC}      docker compose logs -f"
echo -e "  ${BOLD}Stop:${NC}      docker compose down"
echo -e "  ${BOLD}Update:${NC}    docker compose pull && docker compose up -d"
echo ""
echo -e "  ${YELLOW}All connection details and proxy credentials are also${NC}"
echo -e "  ${YELLOW}available in the dashboard after you register.${NC}"
echo ""
